object Versions {
    const val coil = "2.2.0"
    const val splashScreen = "1.0.0-alpha01"
    const val coroutine = "1.7.3"
    const val loggingInterceptor = "4.8.1"
    const val moshiConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val gsonConverter = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val retrofit = "2.9.0"
    const val navigationCompose = "2.8.0"
    const val hiltNavigationCompose = "1.0.0"
    const val hilt = "2.52"
    const val hiltCompiler = "1.0.0-alpha01"
    const val appCompat = "1.6.1"
    const val material = "1.10.0"
    const val coreKtx = "1.10.1"
    const val lifecycleRuntime = "2.6.1"
    const val activityCompose = "1.8.0"
    const val composeBom = "2024.04.01"
    const val junit = "4.13.2"
    const val androidxJunit = "1.1.5"
    const val androidxEspressoCore = "3.5.1"
}
